### ISSUE TITLE
还是关于import error问题,另求环境镜像

### ISSUE THREAD

**Issue by JiachengGU1711** [liuqidong07/MOELoRA-peft#11]
不好意思，前面在忙，现在才转头搞这个代码。。。。
![E~%OR_4RJ3TP6F$X~R8DHTN](https://github.com/liuqidong07/MOELoRA-peft/assets/71056361/c3b21f26-53af-4de8-9541-7d85220f1531)
还是这个错误，我在代码里确实没找到这个变量
![X}Z UEAZKXB(U(QCSPT3{TC](https://github.com/liuqidong07/MOELoRA-peft/assets/71056361/adc4d6ed-2006-49e2-a48c-14e870a2466e)
我试着修改了一下，因为我看都赋同一个值。
然后我接着遇到了下列错误，是因为修改代码的时候疏忽了这里吗？
![RYU6RM4Q3{5)W}3~4C79LVT](https://github.com/liuqidong07/MOELoRA-peft/assets/71056361/5058b5cd-590b-4051-b9fa-9eecdc308869)
最后，这个PeftModelForCausalLMSharedM没在peft_model这个文件内
![QUX5T%(4~1ZYQ5 K`J)4_}T](https://github.com/liuqidong07/MOELoRA-peft/assets/71056361/46220195-cafe-4534-a5b1-cce2eb3a96b2)
另外torch_xla实在有些装不上，能否请有心人给我一个docker或者conda镜像，邮箱：gjcjc8643@gmail.com

**Comment by liuqidong07** [comment]
您好，
1. 第一个问题您的修改是对的，我这次代码更新后修改了这个bug。
2. 第二个问题是您调用prompt tuning了吗。问题出在路径`src.ft_chatglm_lora.xxx`这里，修改为`src.MLoRA.xxx`就可以，我这次代码更新也对这里进行了修正。
3. 实际上PeftModelForCausalLMSharedM是我当时的一个尝试，最终并没有使用这个模型，上传代码时忘记删除这里的import了，这次更新也把这里删除了。
再次感谢您对我们论文的关注以及对代码修改的帮助！祝好！
