### ISSUE TITLE
关于task_num

### ISSUE THREAD

**Issue by Czi24** [liuqidong07/MOELoRA-peft#12]
请问task_num参数做什么的

**Comment by liuqidong07** [comment]
您好，task_num是我们论文中提到的多任务的任务数量。在我们的试验里因为有8个任务，所以这个参数设置为8。

**Comment by Czi24** [comment]
感谢作者开源优秀的项目。

有两个问题请教您一下
1.推理的时候选几个专家呢？，路由在这里需要微调吗，路由有什么作用？
2.Fig. 6怎么可视化的

谢谢您

**Comment by liuqidong07** [comment]
您好，
1. 推理时选用的专家数量与训练时是一样的。在训练时，文中所提的task-motivated是需要更新的，作用简单来说就是为每个task去产生其各自的参数（具体作用可以参考论文中的解释）。
2. Fig.6我是开调试模式，拿到以下这一行的expert_weight后进行可视化的
https://github.com/liuqidong07/MOELoRA-peft/blob/496cf0f3a5d26f54a76868559728c059929929b3/src/MLoRA/peft/peft_model.py#L1284

祝好

**Comment by jiennyteng** [comment]
> 您好，
> 
> 1. 推理时选用的专家数量与训练时是一样的。在训练时，文中所提的task-motivated是需要更新的，作用简单来说就是为每个task去产生其各自的参数（具体作用可以参考论文中的解释）。
> 2. Fig.6我是开调试模式，拿到以下这一行的expert_weight后进行可视化的
>    https://github.com/liuqidong07/MOELoRA-peft/blob/496cf0f3a5d26f54a76868559728c059929929b3/src/MLoRA/peft/peft_model.py#L1284
> 
> 祝好

请问我在训练时需要在数据集中，提供task_id的标注信息吗？如果只是单任务的训练，可以把task_ids 默认为1 吗？
<img width="781" alt="image" src="https://github.com/user-attachments/assets/816c4670-13d7-460f-98fc-b3a093982cac">
