### ISSUE TITLE
请问有人能跑通代码吗，一训练就爆内存，是环境问题？

### ISSUE THREAD

**Issue by Qlb6x** [liuqidong07/MOELoRA-peft#13]
能不能提供一下跑通代码的环境，accelerate，deepspeed，transformers，torch。 

我按照requirements并不能跑通

**Comment by liuqidong07** [comment]
您好，感谢对我们工作的关注。我们的环境配置和readme里写得是一样的，请问您是报爆内存的错误吗？如果尝试调低`--per_device_train_batch_size`和`--max_source_length`参数，看能否先消掉报错？祝好

**Comment by liuqidong07** [comment]
您好，如果依旧存在环境问题，可以在 #7 中继续进行讨论。感谢对我们工作的关注。祝好
