### ISSUE TITLE
请问官方只允许用ChatGLM-6B作为base模型吗？

### ISSUE THREAD

**Issue by Egber1t** [liuqidong07/MOELoRA-peft#14]
是否支持其他开源模型，如Qwen1.5-32B等主流开源模型？谢谢！

**Comment by liuqidong07** [comment]
您好，感谢对我们工作的关注。目前代码只支持ChatGLM-6B，因为需要对基座模型的代码进行修改。

这里我可以给出修改思路：peft包中LoRA的代码逻辑主要是识别基座模型中的所有Linear层，然后把Linear层替换为包装了LoRA的层。因为我们的方法需要给LoRA层额外输入一个task_embedding变量，因此需要修改基座模型，使其中的Linear层再额外接收一个task_embedding的参数。您可以按照这个思路去修改Qwen等基座模型来完成适配。

祝好

**Comment by Egber1t** [comment]
好的，谢谢，感谢指导，祝好！

**Comment by stevenL-1047** [comment]
@Egber1t 请问有成功适配Qwen模型吗？
