### ISSUE TITLE
关于论文中从训练集划分的验证集

### ISSUE THREAD

**Issue by lhyscau** [liuqidong07/MOELoRA-peft#17]
作者你好，请问可以提供论文中提到的验证集吗？以及他是否是用于训练样本的子集？

**Comment by liuqidong07** [comment]
您好，验证集是直接从训练集中划分出来的，所以对训练集进行随机采样即可获得验证集。
祝好

**Comment by lhyscau** [comment]
这里的“划分”，按这个说法，验证集中的样本，模型是见在训练集中“见过”的吗？


SeanLiu
***@***.***

华南农业大学


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuqidong07/MOELoRA-peft"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月24日(星期三) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuqidong07/MOELoRA-peft] 关于论文中从训练集划分的验证集 (Issue #17)





 
您好，验证集是直接从训练集中划分出来的，所以对训练集进行随机采样即可获得验证集。
 祝好

**Comment by lhyscau** [comment]
这里的“划分”，按这个说法，验证集中的样本，模型是见在训练集中“见过”的吗？
如果验证集和训练集是两个独立的部分，在仓库中好像没有找到相关将数据集train.json抽样分割成两部分的代码。
若验证集是训练集的子集，即模型在训练过程中见过了验证集上的数据，那么用训练的数据来验证的目的是什么呢？


SeanLiu
***@***.***

华南农业大学


&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "liuqidong07/MOELoRA-peft"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月24日(星期三) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuqidong07/MOELoRA-peft] 关于论文中从训练集划分的验证集 (Issue #17)





 
您好，验证集是直接从训练集中划分出来的，所以对训练集进行随机采样即可获得验证集。
 祝好
