### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'task_id'

### ISSUE THREAD

**Issue by Bob-Annette** [liuqidong07/MOELoRA-peft#22]
您好！我在复现代码的时候，貌似模型输入没有'task_id'这个参数，请问是什么原因导致的，期待答复，万分感谢！！！

![屏幕截图 2024-11-12 162806](https://github.com/user-attachments/assets/fa23325a-9d66-48e2-9061-dc6cd34e198c)

**Comment by jiennyteng** [comment]
你好，我在复现过程中也遇到了类似的问题，请问task_ids该怎么处理呢？
