### ISSUE TITLE
想求一下作者使用lora以及p-tuning的微调方式的baseline代码

### ISSUE THREAD

**Issue by lhyscau** [liuqidong07/MOELoRA-peft#4]
最近在学习hugging face的peft库的使用方式，不知道作者是使用lora模块在glm上面修改还是直接使用peft库微调呢？两者都想要学习一下。如果可以的话请大佬更新到仓库上或者发到我的邮箱37748250@qq.com。感激不尽！

**Comment by liuqidong07** [comment]
您好，

https://github.com/liuqidong07/MOELoRA-peft/blob/3d130a69c6c7123a375ec3c0d994cb57bbb77d6c/src/MLoRA/main.py#L161
我们的代码本身是支持使用lora的，这里您把lora_name设置一下就可以了。可以看到我们这里使用的是peft微调的。您所说的直接在glm上直接修改的方法我也没有试过。

然后P-tuning的代码您可以参考这个repo的https://github.com/michael-wzhu/PromptCBLUE/tree/main/src。我的代码一开始也是基于这份代码构建的。此外，您也可以参考这个repo：https://github.com/beyondguo/LLM-Tuning来学习glm的微调。

祝好

**Comment by lhyscau** [comment]
感谢作者的解答。我这里说的在glm上直接修改的方法指的是微软仓库中的lora源码的那种方式，因为刚开始学习这方面的知识，还不知道其他人是否是这样做的。

另外我尝试修改成，普通的lora，在单卡3090上面跑，batch_size都设置为1了，刚开始正常训练，训练到大概0.6~0.7个batch_size后，突然爆oom。以及尝试在四卡上面跑moe，都显示以下内容：
`[2024-01-24 12:48:25,368] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 30467`
这是error是在loading checkpoint shards时出现了，模型加载到4/8。

不知道作者有没有遇到过这个情况，在网上说好像是由于CPU内存不足？我看ds.config是基于zero3数据并行的策略，如果改为模型并行的方式是否能够缓解呢？

**Comment by lhyscau** [comment]
我使用双卡跑普通的lora能训练成功了，但有个问题是评估貌似出现了问题。可能是什么原因导致的呢？
![image-20231019151519472](https://github.com/liuqidong07/MOELoRA-peft/assets/81422224/58798a3a-cc0e-4f2c-976f-62259bcf24df)

**Comment by liuqidong07** [comment]
> 我使用双卡跑普通的lora能训练成功了，但有个问题是评估貌似出现了问题。可能是什么原因导致的呢？ ![image-20240125111443403](https://private-user-images.githubusercontent.com/81422224/299526791-4b84d592-0365-4c1a-ad4c-a44eeecc3684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTY5MzEsIm5iZiI6MTcwNjQxNjYzMSwicGF0aCI6Ii84MTQyMjIyNC8yOTk1MjY3OTEtNGI4NGQ1OTItMDM2NS00YzFhLWFkNGMtYTQ0ZWVlY2MzNjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA0MzcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMzk0MzAwYjRlMzE2ZDRlY2FmYjhjOWMzOGU5N2U0YTIzNjhhN2RkYTE3OTFkZWU1NTE0ZTIwNTAwMTlmNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oGu7-J77dUzVtSUYkmJHd22aTo7kX_3xk9WSlzzvuh8)

您好，

评估的话是需要使用`results/evaluation.py`中的评估方法的。自带的这个评估方法其实只对语言生成能力进行了评估。

祝好

**Comment by lhyscau** [comment]
> > 我使用双卡跑普通的lora能训练成功了，但有个问题是评估貌似出现了问题。可能是什么原因导致的呢？ ![image-20240125111443403](https://private-user-images.githubusercontent.com/81422224/299526791-4b84d592-0365-4c1a-ad4c-a44eeecc3684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0MTY5MzEsIm5iZiI6MTcwNjQxNjYzMSwicGF0aCI6Ii84MTQyMjIyNC8yOTk1MjY3OTEtNGI4NGQ1OTItMDM2NS00YzFhLWFkNGMtYTQ0ZWVlY2MzNjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDA0MzcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmMzk0MzAwYjRlMzE2ZDRlY2FmYjhjOWMzOGU5N2U0YTIzNjhhN2RkYTE3OTFkZWU1NTE0ZTIwNTAwMTlmNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oGu7-J77dUzVtSUYkmJHd22aTo7kX_3xk9WSlzzvuh8)
> 
> 您好，
> 
> 评估的话是需要使用`results/evaluation.py`中的评估方法的。自带的这个评估方法其实只对语言生成能力进行了评估。
> 
> 祝好

results/evaluation.py中是一些离散的函数，并没有一个主函数来执行这些函数，是否需要自己来输入参数等来调用里面的方法进行评估呢？

**Comment by liuqidong07** [comment]
您好，

我之前写gitignore时不小心把`results/evaluate.ipynb`屏蔽掉了。我已经将这个script更新上去了，您可以使用这个文件完成自动的测评。

> [`results/evaluate.ipynb`](https://github.com/liuqidong07/MOELoRA-peft/blob/master/results/evaluate.ipynb)

**Comment by Nikol-coder** [comment]
> 感谢作者的解答。我这里说的在glm上直接修改的方法指的是微软仓库中的lora源码的那种方式，因为刚开始学习这方面的知识，还不清楚其他人在微调上是否是这样做的。
> 
> 另外我尝试修改成，普通的lora，在单卡3090上面跑，batch_size都设置为1了，刚开始正常训练，训练到大概0.6~0.7个batch_size后，突然爆oom。以及尝试在四卡上面跑moe，都显示以下内容： `[2024-01-24 12:48:25,368] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 30467` 这是error是在loading checkpoint shards时出现了，模型加载到4/8。
> 
> 以及双卡可跑普通的lora，但是将gpu数量设置为4，跑普通lora时出现以上情况。网上搜索是因为内存太小导致，但是我的拙见是既然在双卡上loading checkpoint shards成功，那么在四卡上应该也问题不大？
> 
> 尚不清楚如何解决，希望作者能提供建议

您好，同学，我看见您在MOELoRA-peft 这个项目上将原来的TPU调用改成了GPU调用，请问能向您咨询方法吗？

**Comment by liuqidong07** [comment]
> > 感谢作者的解答。我这里说的在glm上直接修改的方法指的是微软仓库中的lora源码的那种方式，因为刚开始学习这方面的知识，还不清楚其他人在微调上是否是这样做的。
> > 另外我尝试修改成，普通的lora，在单卡3090上面跑，batch_size都设置为1了，刚开始正常训练，训练到大概0.6~0.7个batch_size后，突然爆oom。以及尝试在四卡上面跑moe，都显示以下内容： `[2024-01-24 12:48:25,368] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 30467` 这是error是在loading checkpoint shards时出现了，模型加载到4/8。
> > 以及双卡可跑普通的lora，但是将gpu数量设置为4，跑普通lora时出现以上情况。网上搜索是因为内存太小导致，但是我的拙见是既然在双卡上loading checkpoint shards成功，那么在四卡上应该也问题不大？
> > 尚不清楚如何解决，希望作者能提供建议
> 
> 您好，同学，我看见您在MOELoRA-peft 这个项目上将原来的TPU调用改成了GPU调用，请问能向您咨询方法吗？

您好，

这个代码一开始就是在GPU上跑的，我没太理解您说原来是TPU调用是在哪里。方便的话可以refer一下是哪几行代码呢？

**Comment by lhyscau** [comment]
> > 感谢作者的解答。我这里说的在glm上直接修改的方法指的是微软仓库中的lora源码的那种方式，因为刚开始学习这方面的知识，还不清楚其他人在微调上是否是这样做的。
> > 另外我尝试修改成，普通的lora，在单卡3090上面跑，batch_size都设置为1了，刚开始正常训练，训练到大概0.6~0.7个batch_size后，突然爆oom。以及尝试在四卡上面跑moe，都显示以下内容： `[2024-01-24 12:48:25,368] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 30467` 这是error是在loading checkpoint shards时出现了，模型加载到4/8。
> > 以及双卡可跑普通的lora，但是将gpu数量设置为4，跑普通lora时出现以上情况。网上搜索是因为内存太小导致，但是我的拙见是既然在双卡上loading checkpoint shards成功，那么在四卡上应该也问题不大？
> > 尚不清楚如何解决，希望作者能提供建议
> 
> 您好，同学，我看见您在MOELoRA-peft 这个项目上将原来的TPU调用改成了GPU调用，请问能向您咨询方法吗？

很久之前把环境调好了不太记得，其实只要GPU环境安装好，自然会跑起来的，TPU的事情不用理会，根据报错调试环境就行
