### ISSUE TITLE
关于代码运行中datasets的一些疑问

### ISSUE THREAD

**Issue by air-tea** [liuqidong07/MOELoRA-peft#5]
作者您好，感谢您杰出的工作。我在运行这份代码的时候遇到了一些困难
![image](https://github.com/liuqidong07/MOELoRA-peft/assets/51868302/6b4415be-4089-42f3-9d8f-fb778ea94ca4)
代码在这里显示报错，我查看后发现datasets路径下只有3个json文件，请问有什么办法能够解决这个问题嘛？

**Comment by lhyscau** [comment]
> 作者您好，感谢您杰出的工作。我在运行这份代码的时候遇到了一些困难 ![image](https://private-user-images.githubusercontent.com/51868302/296792938-6b4415be-4089-42f3-9d8f-fb778ea94ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTA1MjAsIm5iZiI6MTcwNTQ5MDIyMCwicGF0aCI6Ii81MTg2ODMwMi8yOTY3OTI5MzgtNmI0NDE1YmUtNDA4OS00MmYzLTlkOGYtZmI3NzhlYTk0Y2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDExMTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZTJkYjNiNjViZWJkNjY3N2NhZDRlMTMzZTMyNzE2MmUwOGIzYTc2NTgzNWJlNzc4OGQ4YzFlZDc3ODEwYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r3FCqvH_zLp3ACFg1vkwNwBcFJdKiIs7cO4Jf77a_S4) 代码在这里显示报错，我查看后发现datasets路径下只有3个json文件，请问有什么办法能够解决这个问题嘛？

你可以尝试像readme中说的将这三个json文件加入到./data中，之后删除datasets文件夹

**Comment by air-tea** [comment]
您好，做了修改，但是仍然有代码报错。下面是我做出的修改：
![image](https://github.com/liuqidong07/MOELoRA-peft/assets/51868302/999d8054-45b8-4214-8d0c-ec3433cdfdb3)
![image](https://github.com/liuqidong07/MOELoRA-peft/assets/51868302/47230759-9f06-4004-b347-931cf2938cf8)

**Comment by liuqidong07** [comment]
> 作者您好，感谢您杰出的工作。我在运行这份代码的时候遇到了一些困难 ![image](https://private-user-images.githubusercontent.com/51868302/296792938-6b4415be-4089-42f3-9d8f-fb778ea94ca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NDYzNDYsIm5iZiI6MTcwNTY0NjA0NiwicGF0aCI6Ii81MTg2ODMwMi8yOTY3OTI5MzgtNmI0NDE1YmUtNDA4OS00MmYzLTlkOGYtZmI3NzhlYTk0Y2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA2MzQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MTFkYWI2YTU5ODg2MTczMmI4YTQxMWRjMjc3M2FjZWNiOGM4NDY2M2U5MTdiMDM2ZmY3YWZkNTdhZWVhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AZa230-Kp5KbIQDRErfSuek7ruppTp89AYspKIX74t8) 代码在这里显示报错，我查看后发现datasets路径下只有3个json文件，请问有什么办法能够解决这个问题嘛？

您好，

感谢您对我们工作的关注。这里的问题应该是在于datasets本身是一个package，然后我们这里把data的路径错写成了datasets。这个bug我刚已经修复，把data文件夹的名称改了。然后您现在还报错可能是因为没有装datasets这个包，您可以先pip安装一下再跑试试。

祝好
