### ISSUE TITLE
关于总报import error的问题

### ISSUE THREAD

**Issue by JiachengGU1711** [liuqidong07/MOELoRA-peft#8]
让这个代码跑起来搞了2天，经历了apex和deepspeed库的洗礼。好累，现在卡在着。。。。。。。
![QQ图片20240305174628](https://github.com/liuqidong07/MOELoRA-peft/assets/71056361/e6a074f6-df72-41a7-b9c5-ccd22edba4aa)

**Comment by liuqidong07** [comment]
> 让这个代码跑起来搞了2天，经历了apex和deepspeed库的洗礼。好累，现在卡在着。。。。。。。 ![QQ图片20240305174628](https://private-user-images.githubusercontent.com/71056361/310064147-e6a074f6-df72-41a7-b9c5-ccd22edba4aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODMwNzAsIm5iZiI6MTcwOTc4Mjc3MCwicGF0aCI6Ii83MTA1NjM2MS8zMTAwNjQxNDctZTZhMDc0ZjYtZGY3Mi00MWE3LWI5YzUtY2NkMjJlZGJhNGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAzMzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTJiNTkyMDk1YmQzOWFkM2I1N2M5Y2JkYWU3ZjA1NjQwYzI1YjU1ZDk0ZTVhNDM3Y2ZkZDA1MDNjMjM0NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C1bSx85Y5F-KhgvrLa76E08yvOujwZWGJ92H2GrKBIA)

您好，

感觉报这个错可能是python环境的路径没设置对？入口需要甚至到这个项目的文件夹下。

祝好

**Comment by butyuhao** [comment]
我也遇到这个问题，那个文件里头没有这个变量，不晓得作者是怎么跑起来的😂

**Comment by butyuhao** [comment]
![Uploading 截屏2024-03-09 19.48.55.png…]()

**Comment by liuqidong07** [comment]
@butyuhao @JiachengGU1711 抱歉，之前改代码时应该不小心把这个变量删掉了。我把这个bug修复了，可以再试一下。感谢对我们论文的关注！祝好。
