### ISSUE TITLE
评估结果

### ISSUE THREAD

**Issue by lhyscau** [liuqidong07/MOELoRA-peft#9]
### 修改后的evaluate.ipynb脚本
`
import jsonlines
import os
import numpy as np
import pandas as pd
from utils import read_data, extract_data, partition
from evaluation import calculate_score, process_CTC

task_list=('CMeIE', 'CHIP-CDN', 'CHIP-CDEE', 'CHIP-MDCFNPC',
           'CHIP-CTC', 'KUAKE-QIC',
           'IMCS-V2-MRG', 'MedDG',)
pred_path = "pred"
true_path = "true"

target_list = ["test_predictions.json"]

score_dict = {target: [] for target in target_list}
score_dict

score_dict = {target: [] for target in target_list}
label_dict = {}

for target in target_list:
    target_path = os.path.join(pred_path, target)   #pred/task_predictions.json
    
    if not os.path.exists(os.path.join(pred_path, task_list[0])):  # needs partition
        # all_data = read_data(os.path.join(os.path.join(pred_path, "test_predictions.json"))
        all_data = read_data(target_path)
        partition(extract_data(all_data), task_list, pred_path)
    
    for task in task_list:

        pp = os.path.join(target_path, task)
        tp = os.path.join(true_path, task)
        pp = os.path.join("pred", "test_predictions.json")      #pred_path
        tp = os.path.join("pred", "test.json")       #truth_path

        if task == "CHIP-CTC":  # CTC needs post process
            post_process_function = process_CTC
        else:
            post_process_function = None

        score, labels, _ = calculate_score(task, pp, tp, post_process_function)
        score_dict[target].append(score)
        label_dict[task] = labels

import tqdm
# 假设 read_data, save_data, extract_data, partition 函数已经定义
# 请确保这些函数的实现与您之前提供的代码一致

# 假设 pred_path 和 task_list 已经被定义
# pred_path = '/path/to/predictions'  # 预测结果的根目录路径
# task_list = ['task1', 'task2', 'task3']  # 任务列表

# 定义 read_data 函数（示例）
def read_data(data_path):
    with jsonlines.open(data_path, "r") as f:
        data = [meta_data for meta_data in f]
    return data

# 定义 save_data 函数（示例）
def save_data(data_path, data):
    with jsonlines.open(data_path, "w") as w:
        for meta_data in data:
            w.write(meta_data)

# 定义 extract_data 函数（示例）
def extract_data(data):

    data_dict = {}

    for meta_data in data:
        if meta_data['task_dataset'] not in data_dict.keys():
            data_dict[meta_data['task_dataset']] = []
        data_dict[meta_data['task_dataset']].append(meta_data)
    print("extract conpletion")

    return data_dict

# 定义 partition 函数（示例）
def partition(data_dict, task_list, output_path):
    for task in task_list:
        task_path = os.path.join(output_path, task)
        if not os.path.exists(task_path):
            os.makedirs(task_path)

        save_data(os.path.join(task_path, "dev.json"), data_dict[task])

# 主脚本逻辑
# 读取预测结果
target_path = "test.json"  # 预测结果文件路径
all_data = read_data(target_path)

# 提取和组织数据
extracted_data = extract_data(all_data)

# 分区并保存数据
partition(extracted_data, task_list, pred_path)

res_data, res_key = [], []
for key, value in score_dict.items():
    res_data.append(value)
    res_key.append(key)

res_df = pd.DataFrame(columns=task_list,
                      index=res_key,
                      data=res_data)
res_df["average"] = res_df.mean(axis=1)

res_df.head(20)

try:
    new_res_df = res_df.drop(columns=["CHIP-STS", "KUAKE-IR", "average"])
except:
    new_res_df = res_df
new_res_df["average"] = new_res_df.mean(axis=1)
new_res_df.head(50)

for st in ["CHIP-CDN", "CHIP-MDCFNPC", "IMCS-V2-MRG", "KUAKE-QIC"]: 
    score, _, _ = calculate_score(st, 
                                  "pred/%s/test_predictions.json" % st, 
                                  "pred/%s/dev.json" %st, 
                                  post_process_function)
    print("The score for task %s is: %.5f" % (st, score))

`

以上是我对evaluate.ipynb按照自己想法修改的结果，大概意思就是把项目中的‘dev.json’改为使用'test.json'作为ground true，不知道这是不是作者的想法。
最后得到的结果如下图所示：
![image](https://github.com/liuqidong07/MOELoRA-peft/assets/81422224/06062dc3-4006-4932-b719-2a9d24dafcb7)

![image](https://github.com/liuqidong07/MOELoRA-peft/assets/81422224/2729c485-f24e-4e32-972e-6d59fcb1beb2)

我对第二张图的结果有点疑惑，因为test_pretections.json中的target与test.json中的target好像是一模一样的？我看了代码，pretections.json也确实是moe模型生成的答案

**Comment by liuqidong07** [comment]
哈喽，第一个问题把代码中"dev.json"改为"test.json"是我本来的意思，我已经更新上去了，感谢指出。第二个问题的话，请问您是用"train.json"训练的吗，感觉像是把"test.json"里的数据不小心加到训练集里了？大模型的记忆性很强，在训练集上的准确率能达到100%。

**Comment by lhyscau** [comment]
![image](https://github.com/liuqidong07/MOELoRA-peft/assets/81422224/b6b4dc67-c7ee-47a3-9c30-8375c214508e)
感谢东哥！历经两个月终于把你的指标复现了

**Comment by liuqidong07** [comment]
非常感谢对我们论文的关注以及对我们代码的建议，我已经把你的evaluation代码更新上去了。再次表示感谢！
